POST http://localhost:8080/api/product/ HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MmFhMWUyNzA4NzExMGI1MGM1MGQ0MDEiLCJpYXQiOjE2NTU1MTA4OTksImV4cCI6MTY1NTUyNTI5OX0.QnpgReTdl_scpxxjsUWGA-YiTHKgqLxYFaXXKvPxUOI
content-type: application/json

{
    "name": "Karla",
    "category": "62acd46ed1224eb38647df6b"
}